import stopwatch
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\Aadid\Dropbox\PC\Downloads\chronocrank\build\assets\frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("198x324")
window.configure(bg = "#000000")


canvas = Canvas(
    window,
    bg = "#000000",
    height = 324,
    width = 198,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: stopwatch.start_stop_button(),
    relief="flat"
)
button_1.place(
    x=36.0,
    y=204.0,
    width=126.0,
    height=47.0
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: stopwatch.reset(),
    relief="flat"
)
button_2.place(
    x=36.0,
    y=245.0,
    width=126.0,
    height=47.0
)

canvas.create_text(
    44.0,
    99.0,
    anchor="nw",
    text="text",
    fill="#FFFFFF",
    font=("Roboto Medium", 50 * -1)
)

canvas.create_rectangle(
    3.0,
    25.0,
    81.0,
    103.0,
    fill="#FFFFFF",
    outline="")

canvas.create_text(
    97.0,
    315.0,
    anchor="nw",
    text="Material 3 Design Kit by material design",
    fill="#FFFFFF",
    font=("Roboto Medium", 5 * -1)
)
window.resizable(False, False)
window.mainloop()
